-- Chetesaí Fitness+ · ampliación banco maestro de ejercicios (+75; total previsto 105)
-- Idempotente: inserta o actualiza por codigo_interno sin duplicar registros.

insert into public.ejercicios (
  codigo_interno, nombre, grupo_muscular, categoria, dificultad, material,
  tipo_movimiento, lateralidad, plano_movimiento, articulacion_principal,
  descripcion, tecnica, errores_frecuentes, consejos,
  variante_facil, progresion, variante_avanzada, regresion,
  etiquetas, objetivos, apto_casa, apto_gimnasio, nivel_tecnico, riesgo_lesion, activo
)
select
  v.codigo_interno,
  v.nombre,
  v.grupo_muscular,
  v.categoria,
  v.dificultad,
  v.material,
  v.tipo_movimiento,
  v.lateralidad,
  v.plano_movimiento,
  v.articulacion_principal,
  'Ejercicio profesional Chetesaí Fitness+ orientado a ' || v.grupo_muscular || '. Ajustar carga, rango y volumen al nivel del usuario.',
  'Mantener alineación corporal, control excéntrico, respiración continua y un rango de movimiento sin dolor.',
  'Evitar compensaciones; no perder la postura; no utilizar una carga que impida mantener la técnica.',
  'Priorizar calidad de ejecución antes que intensidad y progresar de forma gradual.',
  'Versión asistida o con menor carga',
  'Aumentar gradualmente carga, rango, repeticiones o control',
  'Versión con mayor carga, inestabilidad o demanda técnica',
  'Reducir carga, rango o complejidad',
  array[v.grupo_muscular, v.categoria, v.dificultad]::text[],
  array[v.categoria, 'técnica']::text[],
  case when v.material in ('Barra + rack','Prensa','Máquina','Polea','Polea alta','Polea baja','Trineo','Barra de dominadas','Barra baja') then false else true end,
  true,
  v.dificultad,
  case when v.dificultad = 'avanzado' then 'alto' when v.dificultad = 'intermedio' then 'medio' else 'bajo' end,
  true
from (values
('CHE-PEC-005','Press banca con barra','pecho','fuerza','intermedio','Barra + banco','empuje','bilateral','horizontal','hombro'),
('CHE-PEC-006','Press inclinado con mancuernas','pecho','fuerza','intermedio','Mancuernas + banco inclinado','empuje','bilateral','horizontal','hombro'),
('CHE-PEC-007','Press inclinado con barra','pecho','fuerza','avanzado','Barra + banco inclinado','empuje','bilateral','horizontal','hombro'),
('CHE-PEC-008','Flexiones diamante','pecho','fuerza','intermedio','Sin material','empuje','bilateral','horizontal','codo'),
('CHE-PEC-009','Flexiones declinadas','pecho','fuerza','avanzado','Banco','empuje','bilateral','horizontal','hombro'),
('CHE-PEC-010','Cruce de poleas','pecho','fuerza','intermedio','Poleas','aislamiento','bilateral','horizontal','hombro'),
('CHE-PEC-011','Press en máquina convergente','pecho','fuerza','principiante','Máquina','empuje','bilateral','horizontal','hombro'),
('CHE-PEC-012','Pullover con mancuerna','pecho','fuerza','intermedio','Mancuerna + banco','aislamiento','bilateral','sagital','hombro'),
('CHE-ESP-005','Remo con barra','espalda','fuerza','avanzado','Barra','traccion','bilateral','horizontal','hombro'),
('CHE-ESP-006','Remo sentado en polea','espalda','fuerza','principiante','Polea baja','traccion','bilateral','horizontal','hombro'),
('CHE-ESP-007','Remo en máquina','espalda','fuerza','principiante','Máquina','traccion','bilateral','horizontal','hombro'),
('CHE-ESP-008','Jalón agarre neutro','espalda','fuerza','intermedio','Polea alta','traccion','bilateral','vertical','hombro'),
('CHE-ESP-009','Dominadas supinas','espalda','fuerza','avanzado','Barra','traccion','bilateral','vertical','hombro'),
('CHE-ESP-010','Pullover en polea','espalda','fuerza','intermedio','Polea alta','aislamiento','bilateral','sagital','hombro'),
('CHE-ESP-011','Face pull','espalda','fuerza','principiante','Polea o banda','traccion','bilateral','horizontal','hombro'),
('CHE-ESP-012','Remo invertido','espalda','fuerza','intermedio','Barra baja','traccion','bilateral','horizontal','hombro'),
('CHE-ESP-013','Encogimientos escapulares en barra','espalda','fuerza','principiante','Barra de dominadas','traccion','bilateral','vertical','hombro'),
('CHE-HOM-004','Press Arnold','hombros','fuerza','intermedio','Mancuernas','empuje','bilateral','vertical','hombro'),
('CHE-HOM-005','Elevación frontal','hombros','fuerza','principiante','Mancuernas o disco','aislamiento','bilateral','sagital','hombro'),
('CHE-HOM-006','Elevación lateral en polea','hombros','fuerza','intermedio','Polea baja','aislamiento','unilateral','frontal','hombro'),
('CHE-HOM-007','Press militar con barra','hombros','fuerza','avanzado','Barra','empuje','bilateral','vertical','hombro'),
('CHE-HOM-008','Remo al mentón con agarre amplio','hombros','fuerza','intermedio','Barra o polea','traccion','bilateral','vertical','hombro'),
('CHE-HOM-009','Rotación externa con banda','hombros','rehabilitacion','principiante','Banda elástica','movilidad','unilateral','transversal','hombro'),
('CHE-HOM-010','Y-raise inclinado','hombros','fuerza','intermedio','Mancuernas ligeras','aislamiento','bilateral','multiplanar','hombro'),
('CHE-HOM-011','Pike push-up','hombros','fuerza','intermedio','Sin material','empuje','bilateral','vertical','hombro'),
('CHE-PIE-007','Sentadilla libre','piernas','fuerza','principiante','Sin material','sentadilla','bilateral','sagital','cadera/rodilla'),
('CHE-PIE-008','Sentadilla con barra trasera','piernas','fuerza','avanzado','Barra + rack','sentadilla','bilateral','sagital','cadera/rodilla'),
('CHE-PIE-009','Sentadilla frontal','piernas','fuerza','avanzado','Barra + rack','sentadilla','bilateral','sagital','cadera/rodilla'),
('CHE-PIE-010','Prensa de piernas','piernas','fuerza','principiante','Prensa','sentadilla','bilateral','sagital','cadera/rodilla'),
('CHE-PIE-011','Extensión de cuádriceps','piernas','fuerza','principiante','Máquina','aislamiento','bilateral','sagital','rodilla'),
('CHE-PIE-012','Curl femoral tumbado','piernas','fuerza','principiante','Máquina','aislamiento','bilateral','sagital','rodilla'),
('CHE-PIE-013','Curl femoral sentado','piernas','fuerza','principiante','Máquina','aislamiento','bilateral','sagital','rodilla'),
('CHE-PIE-014','Peso muerto convencional','piernas','fuerza','avanzado','Barra','bisagra','bilateral','sagital','cadera'),
('CHE-PIE-015','Peso muerto sumo','piernas','fuerza','avanzado','Barra','bisagra','bilateral','sagital','cadera'),
('CHE-PIE-016','Zancada caminando','piernas','fuerza','intermedio','Sin material o mancuernas','zancada','alterno','sagital','cadera/rodilla'),
('CHE-PIE-017','Zancada lateral','piernas','fuerza','intermedio','Sin material','zancada','unilateral','frontal','cadera/rodilla'),
('CHE-PIE-018','Sentadilla búlgara','piernas','fuerza','intermedio','Banco','zancada','unilateral','sagital','cadera/rodilla'),
('CHE-PIE-019','Buenos días','piernas','fuerza','intermedio','Barra ligera','bisagra','bilateral','sagital','cadera'),
('CHE-PIE-020','Elevación de gemelos de pie','piernas','fuerza','principiante','Sin material o máquina','aislamiento','bilateral','sagital','tobillo'),
('CHE-PIE-021','Elevación de gemelos sentado','piernas','fuerza','principiante','Máquina o mancuerna','aislamiento','bilateral','sagital','tobillo'),
('CHE-GLU-001','Puente de glúteos','gluteos','fuerza','principiante','Sin material','bisagra','bilateral','sagital','cadera'),
('CHE-GLU-002','Abducción de cadera con banda','gluteos','fuerza','principiante','Banda elástica','aislamiento','bilateral','frontal','cadera'),
('CHE-GLU-003','Patada de glúteo en polea','gluteos','fuerza','intermedio','Polea baja','aislamiento','unilateral','sagital','cadera'),
('CHE-BRA-005','Curl con barra','biceps','fuerza','intermedio','Barra','aislamiento','bilateral','sagital','codo'),
('CHE-BRA-006','Curl predicador','biceps','fuerza','intermedio','Banco predicador + barra','aislamiento','bilateral','sagital','codo'),
('CHE-BRA-007','Curl inclinado','biceps','fuerza','intermedio','Mancuernas + banco','aislamiento','bilateral','sagital','codo'),
('CHE-BRA-008','Curl en polea','biceps','fuerza','principiante','Polea baja','aislamiento','bilateral','sagital','codo'),
('CHE-BRA-009','Press francés','triceps','fuerza','intermedio','Barra Z + banco','empuje','bilateral','sagital','codo'),
('CHE-BRA-010','Fondos en banco','triceps','fuerza','principiante','Banco','empuje','bilateral','sagital','codo'),
('CHE-BRA-011','Press cerrado','triceps','fuerza','intermedio','Barra + banco','empuje','bilateral','horizontal','codo'),
('CHE-BRA-012','Extensión unilateral en polea','triceps','fuerza','principiante','Polea','aislamiento','unilateral','sagital','codo'),
('CHE-BRA-013','Curl Zottman','biceps','fuerza','intermedio','Mancuernas','aislamiento','bilateral','sagital','codo'),
('CHE-BRA-014','Curl concentración','biceps','fuerza','principiante','Mancuerna','aislamiento','unilateral','sagital','codo'),
('CHE-COR-006','Crunch abdominal','core','fuerza','principiante','Sin material','aislamiento','bilateral','sagital','columna'),
('CHE-COR-007','Crunch en polea','core','fuerza','intermedio','Polea alta','aislamiento','bilateral','sagital','columna'),
('CHE-COR-008','Elevación de piernas tumbado','core','fuerza','intermedio','Sin material','aislamiento','bilateral','sagital','cadera'),
('CHE-COR-009','Elevación de rodillas colgado','core','fuerza','avanzado','Barra','aislamiento','bilateral','sagital','cadera'),
('CHE-COR-010','Hollow hold','core','fuerza','intermedio','Sin material','aislamiento','bilateral','sagital','columna'),
('CHE-COR-011','Mountain climber','core','fuerza','intermedio','Sin material','locomocion','alterno','sagital','cadera'),
('CHE-COR-012','Russian twist','core','fuerza','intermedio','Sin material o balón','rotacion','alterno','transversal','columna'),
('CHE-COR-013','Woodchop en polea','core','fuerza','intermedio','Polea','rotacion','unilateral','transversal','columna'),
('CHE-COR-014','Suitcase carry','core','fuerza','intermedio','Mancuerna o kettlebell','locomocion','unilateral','frontal','columna'),
('CHE-COR-015','Ab wheel rollout','core','fuerza','avanzado','Rueda abdominal','aislamiento','bilateral','sagital','columna'),
('CHE-MOV-003','90/90 de cadera','piernas','movilidad','principiante','Sin material','movilidad','bilateral','multiplanar','cadera'),
('CHE-MOV-004','Estiramiento flexor de cadera','piernas','estiramiento','principiante','Sin material','movilidad','unilateral','sagital','cadera'),
('CHE-MOV-005','Movilidad de tobillo rodilla a pared','piernas','movilidad','principiante','Pared','movilidad','unilateral','sagital','tobillo'),
('CHE-MOV-006','Wall slides','hombros','movilidad','principiante','Pared','movilidad','bilateral','frontal','hombro'),
('CHE-MOV-007','Thread the needle','espalda','movilidad','principiante','Sin material','rotacion','unilateral','transversal','columna'),
('CHE-MOV-008','Cobra suave','core','movilidad','principiante','Sin material','movilidad','bilateral','sagital','columna'),
('CHE-MOV-009','Estiramiento dorsal en banco','espalda','estiramiento','principiante','Banco','movilidad','bilateral','sagital','hombro'),
('CHE-FUN-003','Sled push','cuerpo_completo','fuerza','intermedio','Trineo','locomocion','bilateral','sagital','cadera'),
('CHE-FUN-004','Bear crawl','cuerpo_completo','fuerza','intermedio','Sin material','locomocion','alterno','multiplanar','hombro'),
('CHE-FUN-005','Turkish get-up','cuerpo_completo','fuerza','avanzado','Kettlebell','locomocion','unilateral','multiplanar','hombro'),
('CHE-CAR-001','Jumping jacks','cardio','cardio','principiante','Sin material','locomocion','bilateral','frontal','cadera'),
('CHE-CAR-002','Burpee','cuerpo_completo','cardio','avanzado','Sin material','locomocion','bilateral','multiplanar','cadera')
) as v(codigo_interno,nombre,grupo_muscular,categoria,dificultad,material,tipo_movimiento,lateralidad,plano_movimiento,articulacion_principal)
on conflict (codigo_interno) do update set
  nombre = excluded.nombre,
  grupo_muscular = excluded.grupo_muscular,
  categoria = excluded.categoria,
  dificultad = excluded.dificultad,
  material = excluded.material,
  tipo_movimiento = excluded.tipo_movimiento,
  lateralidad = excluded.lateralidad,
  plano_movimiento = excluded.plano_movimiento,
  articulacion_principal = excluded.articulacion_principal,
  descripcion = excluded.descripcion,
  tecnica = excluded.tecnica,
  errores_frecuentes = excluded.errores_frecuentes,
  consejos = excluded.consejos,
  variante_facil = excluded.variante_facil,
  progresion = excluded.progresion,
  variante_avanzada = excluded.variante_avanzada,
  regresion = excluded.regresion,
  etiquetas = excluded.etiquetas,
  objetivos = excluded.objetivos,
  apto_casa = excluded.apto_casa,
  apto_gimnasio = excluded.apto_gimnasio,
  nivel_tecnico = excluded.nivel_tecnico,
  riesgo_lesion = excluded.riesgo_lesion,
  activo = excluded.activo,
  updated_at = now();
