-- Chetesaí Fitness+ · calentamiento y estiramientos
-- 32 ejercicios nuevos: 16 de calentamiento + 16 de estiramiento.
-- Idempotente por codigo_interno.

insert into public.ejercicios (
  codigo_interno, nombre, grupo_muscular, grupo_secundario, categoria, dificultad, material,
  descripcion, tecnica, errores_frecuentes, consejos, tipo_movimiento, lateralidad,
  plano_movimiento, articulacion_principal, variante_facil, progresion, variante_avanzada,
  regresion, etiquetas, objetivos, apto_casa, apto_gimnasio, nivel_tecnico, riesgo_lesion, activo
) values
-- CALENTAMIENTO
('CHE-WRM-001','Marcha activa con braceo','cuerpo_completo',NULL,'cardio','principiante','Sin material','Activación general de baja intensidad para elevar progresivamente temperatura corporal y frecuencia cardiaca.','Marcha con postura erguida, braceo natural y apoyo completo del pie durante 60-120 segundos.','Acelerar demasiado; encorvar el tronco; contener la respiración','Comienza suave y aumenta el ritmo de forma progresiva.','locomocion','alterno','sagital','cadera/rodilla','Marcha lenta','Marcha rápida','Skipping bajo','Marcha lenta',ARRAY['calentamiento','activacion_general','cardio']::text[],ARRAY['calentamiento','temperatura corporal']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-002','Jumping jack suave','cuerpo_completo',NULL,'cardio','principiante','Sin material','Activación cardiovascular coordinada con movimiento de brazos y piernas.','Abre piernas y eleva brazos de forma simultánea, aterrizando suave y manteniendo ritmo cómodo.','Impacto excesivo; rodillas hacia dentro; ritmo demasiado alto','Usa una variante sin salto si necesitas reducir impacto.','locomocion','bilateral','frontal','cadera/hombro','Paso lateral sin salto','Jumping jack estándar','Jumping jack rápido','Paso lateral sin salto',ARRAY['calentamiento','activacion_general','cardio']::text[],ARRAY['calentamiento','coordinación']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-003','Movilidad cervical controlada','cuerpo_completo',NULL,'movilidad','principiante','Sin material','Movilidad suave de cuello para reducir rigidez antes de la sesión.','Realiza flexión, extensión suave e inclinaciones laterales dentro de un rango cómodo.','Hacer círculos rápidos; forzar el final del rango; elevar hombros','Movimiento lento y sin dolor.','movilidad','bilateral','multiplanar','columna cervical','Rango corto','Rango completo controlado','Isométricos cervicales suaves','Rango corto',ARRAY['calentamiento','movilidad','cervical']::text[],ARRAY['movilidad','preparación articular']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-004','Círculos de hombros','hombros',NULL,'movilidad','principiante','Sin material','Preparación del complejo escapulohumeral antes de empujes y tracciones.','Realiza círculos amplios y lentos hacia delante y atrás sin elevar excesivamente los hombros.','Mover solo los codos; dolor; velocidad excesiva','Prioriza amplitud cómoda y respiración fluida.','movilidad','bilateral','multiplanar','hombro','Círculos pequeños','Círculos completos','Círculos con banda ligera','Círculos pequeños',ARRAY['calentamiento','movilidad','hombros']::text[],ARRAY['movilidad','preparación hombro']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-005','Rotación torácica de pie','espalda',NULL,'movilidad','principiante','Sin material','Activa movilidad torácica y control de rotación antes de movimientos globales.','Con pies estables, rota el tronco de lado a lado manteniendo pelvis relativamente orientada al frente.','Rotar desde rodillas; forzar zona lumbar; movimientos bruscos','Busca rotación torácica, no amplitud máxima.','rotacion','alterno','transversal','columna torácica','Rango corto','Rotación completa','Rotación con banda','Rango corto',ARRAY['calentamiento','movilidad','toracica']::text[],ARRAY['movilidad','rotación']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-006','Balanceo frontal de pierna','piernas',NULL,'movilidad','principiante','Apoyo opcional','Movilidad dinámica de cadera e isquiotibiales.','Sujétate si es necesario y balancea una pierna adelante y atrás con control, sin arquear la espalda.','Usar impulso excesivo; inclinar el tronco; perder equilibrio','Empieza con poca amplitud y aumenta gradualmente.','movilidad','unilateral','sagital','cadera','Balanceo corto','Balanceo controlado completo','Balanceo sin apoyo','Balanceo corto',ARRAY['calentamiento','movilidad','cadera']::text[],ARRAY['movilidad','cadena posterior']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-007','Balanceo lateral de pierna','piernas',NULL,'movilidad','principiante','Apoyo opcional','Preparación dinámica de abductores, aductores y cadera.','Balancea una pierna lateralmente cruzando suavemente la línea media sin girar el tronco.','Girar pelvis en exceso; perder control; amplitud forzada','Mantén el tronco estable.','movilidad','unilateral','frontal','cadera','Rango corto','Balanceo lateral completo','Sin apoyo','Rango corto',ARRAY['calentamiento','movilidad','cadera']::text[],ARRAY['movilidad','plano frontal']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-008','Rodilla a pared dinámica','piernas',NULL,'movilidad','principiante','Pared','Movilidad de dorsiflexión del tobillo antes de sentadillas, zancadas y carrera.','Acerca la rodilla a la pared manteniendo el talón en contacto con el suelo y vuelve.','Levantar talón; colapsar arco plantar; forzar dolor','Alinea rodilla con segundo-tercer dedo del pie.','movilidad','unilateral','sagital','tobillo','Menor distancia','Mayor distancia controlada','Con carga ligera','Menor distancia',ARRAY['calentamiento','movilidad','tobillo']::text[],ARRAY['movilidad','sentadilla']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-009','Sentadilla profunda asistida dinámica','piernas',NULL,'movilidad','principiante','Soporte estable opcional','Integra movilidad de tobillo, rodilla y cadera en patrón de sentadilla.','Desciende a una sentadilla cómoda, mantén un instante y vuelve sin rebote.','Talones elevados; rodillas hacia dentro; lumbar redondeada en exceso','Usa apoyo si mejora la calidad del movimiento.','sentadilla','bilateral','sagital','cadera/rodilla','Sentadilla parcial','Sentadilla profunda controlada','Sentadilla con alcance','Sentadilla parcial',ARRAY['calentamiento','movilidad','sentadilla']::text[],ARRAY['calentamiento','patrón de sentadilla']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-010','Zancada con rotación torácica','cuerpo_completo',NULL,'movilidad','intermedio','Sin material','Movilidad dinámica integrada de cadera y columna torácica.','Da una zancada larga y rota el tronco hacia la pierna adelantada manteniendo control de pelvis y rodilla.','Rodilla colapsa; rotar desde lumbar; perder equilibrio','Reduce el rango antes que perder estabilidad.','zancada','alterno','multiplanar','cadera/columna','Zancada sin rotación','Zancada con rotación','World greatest stretch fluido','Zancada sin rotación',ARRAY['calentamiento','movilidad','cadera','toracica']::text[],ARRAY['calentamiento','movilidad global']::text[],true,true,'intermedio','bajo',true),
('CHE-WRM-011','Puente de glúteos de activación','gluteos',NULL,'fuerza','principiante','Sin material','Activación del glúteo mayor antes de patrones de bisagra, carrera o tren inferior.','Eleva la cadera apretando glúteos y manteniendo costillas controladas; baja lentamente.','Hiperextender lumbar; empujar solo con isquios; abrir costillas','Haz 8-15 repeticiones lentas.','bisagra','bilateral','sagital','cadera','Puente corto','Puente completo','Puente unilateral','Puente corto',ARRAY['calentamiento','activacion','gluteos']::text[],ARRAY['activación muscular','cadera']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-012','Caminata lateral con minibanda','gluteos',NULL,'fuerza','principiante','Minibanda','Activación de glúteo medio y control frontal de cadera.','Mantén ligera flexión de cadera y rodillas y desplázate lateralmente sin juntar completamente los pies.','Rodillas colapsan; pasos demasiado grandes; balanceo del tronco','Mantén tensión constante en la banda.','locomocion','bilateral','frontal','cadera','Sin banda','Minibanda suave','Banda más resistente','Sin banda',ARRAY['calentamiento','activacion','gluteos']::text[],ARRAY['activación muscular','estabilidad cadera']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-013','Dead bug de activación','core',NULL,'fuerza','principiante','Sin material','Activa control lumbopélvico antes de levantar cargas o entrenar cuerpo completo.','Extiende brazo y pierna contrarios manteniendo pelvis estable y respiración controlada.','Arquear lumbar; velocidad excesiva; contener respiración','Exhala al extender.','anti_extension','alterno','sagital','columna/pelvis','Solo brazos','Dead bug completo','Con banda ligera','Solo brazos',ARRAY['calentamiento','activacion','core']::text[],ARRAY['activación muscular','control lumbopélvico']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-014','Scapular push-up','hombros',NULL,'fuerza','principiante','Sin material','Activa serrato anterior y control escapular antes de presses y flexiones.','Desde posición de plancha alta, separa y aproxima escápulas sin doblar codos.','Flexionar codos; hundir lumbar; elevar hombros','Mantén cuello largo y codos extendidos.','empuje','bilateral','horizontal','escapula','Apoyo en pared','Plancha alta','Con banda','Apoyo en pared',ARRAY['calentamiento','activacion','escapular']::text[],ARRAY['activación muscular','estabilidad hombro']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-015','Remo con banda de activación','espalda',NULL,'fuerza','principiante','Banda elástica','Activación ligera de espalda media antes de tracciones.','Tira de la banda llevando codos atrás y junta suavemente las escápulas.','Encoger hombros; hiperextender lumbar; exceso de tensión','Usa resistencia ligera y 10-15 repeticiones.','traccion','bilateral','horizontal','hombro/escapula','Banda muy suave','Banda suave','Pausa isométrica','Banda muy suave',ARRAY['calentamiento','activacion','espalda']::text[],ARRAY['activación muscular','escápulas']::text[],true,true,'principiante','bajo',true),
('CHE-WRM-016','Skipping bajo','cardio',NULL,'cardio','intermedio','Sin material','Aproximación dinámica a carrera y sesiones cardiovasculares.','Eleva rodillas de forma moderada con contactos rápidos y suaves, manteniendo tronco erguido.','Impacto fuerte; inclinarse atrás; elevar demasiado las rodillas','Empieza con 15-30 segundos y progresa.','locomocion','alterno','sagital','cadera/tobillo','Marcha rápida','Skipping bajo','Skipping alto','Marcha rápida',ARRAY['calentamiento','activacion_general','cardio','running']::text[],ARRAY['calentamiento','coordinación','carrera']::text[],true,true,'intermedio','medio',true),

-- ESTIRAMIENTOS
('CHE-STR-001','Estiramiento de pectoral en pared','pecho',NULL,'estiramiento','principiante','Pared','Estiramiento estático suave del pectoral y región anterior del hombro.','Apoya antebrazo en la pared y gira suavemente el tronco hasta notar tensión tolerable en el pecho.','Forzar hombro; elevar hombro; rebotes','Mantén 20-40 segundos respirando con normalidad.','movilidad','unilateral','transversal','hombro','Menor rotación','Mayor rotación cómoda','Brazo algo más alto o bajo según objetivo','Menor rotación',ARRAY['estiramientos','pecho','vuelta_calma']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-002','Estiramiento dorsal en banco','espalda',NULL,'estiramiento','principiante','Banco o silla','Estiramiento de dorsal ancho y hombros con apoyo estable.','Apoya manos en banco y lleva cadera atrás mientras desciendes el pecho de forma controlada.','Hundir lumbar; forzar hombros; bloquear respiración','Mantén abdomen suave pero controlado.','movilidad','bilateral','sagital','hombro','Menor inclinación','Mayor rango cómodo','Con ligera rotación lateral','Menor inclinación',ARRAY['estiramientos','espalda','vuelta_calma']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-003','Estiramiento de tríceps sobre cabeza','triceps',NULL,'estiramiento','principiante','Sin material','Estiramiento suave del tríceps y región posterior del hombro.','Flexiona un codo detrás de la cabeza y aplica una presión ligera con la otra mano.','Tirar fuerte del codo; arquear lumbar; dolor de hombro','Mantén costillas controladas.','movilidad','unilateral','sagital','hombro/codo','Sin presión adicional','Presión ligera','Inclinación lateral suave','Sin presión adicional',ARRAY['estiramientos','triceps','hombros']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-004','Estiramiento de deltoides posterior','hombros',NULL,'estiramiento','principiante','Sin material','Estiramiento transversal del hombro posterior.','Cruza un brazo por delante del pecho y aproxímalo suavemente con el otro brazo.','Elevar hombro; rotar tronco; dolor','Mantén la escápula relajada.','movilidad','unilateral','horizontal','hombro','Menor presión','Presión ligera','Variar ángulo del brazo','Menor presión',ARRAY['estiramientos','hombros','vuelta_calma']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-005','Estiramiento cervical lateral','cuerpo_completo',NULL,'estiramiento','principiante','Sin material','Descarga suave de musculatura cervical y trapecio superior.','Inclina la cabeza hacia un lado manteniendo hombros relajados y mirada al frente.','Tirar fuerte de la cabeza; girar cuello; elevar hombro','La mano puede acompañar sin ejercer fuerza.','movilidad','unilateral','frontal','columna cervical','Sin ayuda de mano','Ayuda mínima','Añadir ligera rotación','Sin ayuda de mano',ARRAY['estiramientos','cervical','vuelta_calma']::text[],ARRAY['movilidad','relajación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-006','Postura del niño','espalda',NULL,'estiramiento','principiante','Colchoneta','Movilidad suave de espalda, cadera y hombros durante la vuelta a la calma.','Lleva cadera hacia talones y extiende brazos al frente manteniendo respiración lenta.','Forzar rodillas; hundir hombros; contener respiración','Separa rodillas si mejora la comodidad.','movilidad','bilateral','sagital','cadera/columna','Cadera menos atrás','Postura completa','Desplazar manos a un lado para dorsal','Cadera menos atrás',ARRAY['estiramientos','espalda','cadera','vuelta_calma']::text[],ARRAY['movilidad','respiración']::text[],true,true,'principiante','bajo',true),
('CHE-STR-007','Estiramiento flexor de cadera en media rodilla','piernas',NULL,'estiramiento','principiante','Colchoneta','Estiramiento de flexores de cadera tras trabajo prolongado de carrera, zancadas o sedestación.','En media rodilla, realiza ligera retroversión pélvica y desplaza el cuerpo hacia delante sin arquear lumbar.','Hiperextender lumbar; avanzar demasiado; perder pelvis neutra','Piensa en acercar pubis hacia ombligo antes de avanzar.','movilidad','unilateral','sagital','cadera','Menor desplazamiento','Rango completo cómodo','Brazo del lado estirado arriba','Menor desplazamiento',ARRAY['estiramientos','piernas','cadera','vuelta_calma']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-008','Estiramiento de cuádriceps de pie','piernas',NULL,'estiramiento','principiante','Apoyo opcional','Estiramiento estático del cuádriceps y recto femoral.','Sujeta el tobillo y acerca talón a glúteo manteniendo rodillas próximas y pelvis controlada.','Arquear lumbar; separar rodillas; tirar del pie con fuerza','Usa apoyo para mejorar equilibrio.','movilidad','unilateral','sagital','rodilla/cadera','Con apoyo','Sin apoyo','Ligera extensión de cadera','Con apoyo',ARRAY['estiramientos','piernas','cuadriceps']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-009','Estiramiento de isquiotibiales tumbado','piernas',NULL,'estiramiento','principiante','Toalla o banda opcional','Estiramiento controlado de isquiotibiales con columna apoyada.','Eleva una pierna extendida hasta notar tensión tolerable manteniendo pelvis estable.','Despegar pelvis; bloquear rodilla con dolor; tirar fuerte','Mantén una ligera flexión de rodilla si lo necesitas.','movilidad','unilateral','sagital','cadera/rodilla','Rodilla flexionada','Pierna más extendida','Con banda','Rodilla flexionada',ARRAY['estiramientos','piernas','isquiotibiales']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-010','Estiramiento de glúteo figura cuatro','gluteos',NULL,'estiramiento','principiante','Colchoneta','Estiramiento de glúteos y rotadores externos de cadera.','Tumbado, cruza un tobillo sobre la rodilla contraria y acerca la pierna hacia el tronco.','Forzar rodilla cruzada; levantar cabeza; contener respiración','Mantén cuello relajado.','movilidad','unilateral','multiplanar','cadera','Menor aproximación','Figura cuatro completa','Versión sentada','Menor aproximación',ARRAY['estiramientos','gluteos','cadera']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-011','Estiramiento de aductores mariposa','piernas',NULL,'estiramiento','principiante','Colchoneta','Estiramiento suave de aductores y región medial de cadera.','Junta plantas de los pies, mantén espalda larga y deja caer rodillas sin empujarlas.','Presionar rodillas con fuerza; redondear espalda; rebotes','Acerca o aleja los pies para regular intensidad.','movilidad','bilateral','frontal','cadera','Pies más lejos','Pies más cerca','Inclinación anterior suave','Pies más lejos',ARRAY['estiramientos','piernas','aductores']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-012','Estiramiento de gemelo en pared','piernas',NULL,'estiramiento','principiante','Pared','Estiramiento del gastrocnemio con talón apoyado.','Coloca una pierna atrás, mantén rodilla extendida y talón en el suelo mientras avanzas el cuerpo.','Talón elevado; pie girado; rebote','Mantén el pie posterior orientado al frente.','movilidad','unilateral','sagital','tobillo','Menor distancia','Mayor distancia','Versión sóleo con rodilla flexionada','Menor distancia',ARRAY['estiramientos','piernas','gemelos']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-013','Estiramiento de sóleo en pared','piernas',NULL,'estiramiento','principiante','Pared','Estiramiento específico de sóleo mediante flexión de rodilla.','Con pie posterior apoyado, flexiona ligeramente la rodilla manteniendo el talón en el suelo.','Levantar talón; colapsar arco; forzar tobillo','Mantén movimiento pequeño y controlado.','movilidad','unilateral','sagital','tobillo','Menor flexión','Mayor flexión cómoda','Sin apoyo de manos','Menor flexión',ARRAY['estiramientos','piernas','soleo']::text[],ARRAY['movilidad','recuperación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-014','Rotación lumbar tumbado suave','core',NULL,'estiramiento','principiante','Colchoneta','Movilidad suave de tronco y cadera para vuelta a la calma.','Tumbado boca arriba, lleva rodillas flexionadas hacia un lado manteniendo hombros apoyados.','Forzar rodillas al suelo; dolor lumbar; contener respiración','Reduce el rango si despega el hombro contrario.','rotacion','bilateral','transversal','columna/cadera','Rango corto','Rango completo cómodo','Pierna superior extendida','Rango corto',ARRAY['estiramientos','core','espalda','vuelta_calma']::text[],ARRAY['movilidad','relajación']::text[],true,true,'principiante','bajo',true),
('CHE-STR-015','Cobra suave','core',NULL,'estiramiento','principiante','Colchoneta','Extensión suave del tronco y región anterior abdominal.','Desde prono, eleva el pecho con apoyo de antebrazos o manos sin comprimir la zona lumbar.','Bloquear codos; dolor lumbar; elevar hombros','Usa antebrazos si necesitas menos extensión.','movilidad','bilateral','sagital','columna','Esfinge','Cobra suave','Cobra con mayor extensión tolerable','Esfinge',ARRAY['estiramientos','core','movilidad']::text[],ARRAY['movilidad','vuelta calma']::text[],true,true,'principiante','bajo',true),
('CHE-STR-016','Respiración diafragmática tumbado','core',NULL,'movilidad','principiante','Colchoneta','Ejercicio de respiración para reducir activación al finalizar la sesión.','Tumbado boca arriba, inspira por nariz expandiendo abdomen y costillas bajas; espira lentamente sin tensión.','Elevar hombros; respiración rápida; forzar inhalación','Realiza 5-10 ciclos lentos y cómodos.','movilidad','bilateral','multiplanar','diafragma','Respiración natural','Exhalación prolongada','Respiración 4-6 segundos','Respiración natural',ARRAY['estiramientos','respiracion','vuelta_calma']::text[],ARRAY['respiración','recuperación']::text[],true,true,'principiante','bajo',true)

on conflict (codigo_interno) where codigo_interno is not null do update set
  nombre=excluded.nombre,
  grupo_muscular=excluded.grupo_muscular,
  grupo_secundario=excluded.grupo_secundario,
  categoria=excluded.categoria,
  dificultad=excluded.dificultad,
  material=excluded.material,
  descripcion=excluded.descripcion,
  tecnica=excluded.tecnica,
  errores_frecuentes=excluded.errores_frecuentes,
  consejos=excluded.consejos,
  tipo_movimiento=excluded.tipo_movimiento,
  lateralidad=excluded.lateralidad,
  plano_movimiento=excluded.plano_movimiento,
  articulacion_principal=excluded.articulacion_principal,
  variante_facil=excluded.variante_facil,
  progresion=excluded.progresion,
  variante_avanzada=excluded.variante_avanzada,
  regresion=excluded.regresion,
  etiquetas=excluded.etiquetas,
  objetivos=excluded.objetivos,
  apto_casa=excluded.apto_casa,
  apto_gimnasio=excluded.apto_gimnasio,
  nivel_tecnico=excluded.nivel_tecnico,
  riesgo_lesion=excluded.riesgo_lesion,
  activo=excluded.activo,
  updated_at=now();
